version: '3'
services:
  web:
    image: python:3.12-alpine
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./app.py:/app/app.py
    command: >
      sh -c "pip install -r requirements.txt && python app.py"